version: "3.9"
services:
  db:
    image: postgres:alpine3.15
    ports:
      - "5432:5432"
    volumes:
      - ~/data:/var/lib/postgresql
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
